---
title: "Consultant & Judge Information"
subtitle: https://norcaldatafest.netlify.com/
output:
  html_document: default
  pdf_document: default
---

# General Event Info 

All information regarding the event can be found at https://norcaldatafest.netlify.com/.

### Location

<!---

Throughout the weekend students will work in the event room on campus. There are many places to park around campus. [Here is a link to an interactive map showing the event location and recommended parking.](https://www.google.com/maps/d/u/0/edit?mid=1T37DrPBRhMhvMuvecZpQqAjh7Ilq63c&usp=sharing) 

--->

Throughout the weekend students will work in the event room on campus. There are many places to park around campus and downtown. [Here is a link to an interactive map showing the cafe, and parking nearby.](https://www.csuchico.edu/maps/campus/?id=1193#!m/316229?ce/0,31642,28505?ct/28506,36245,36247,36246,36473,36472,32703,32116,32115,32092,32068,32015,31198?mc/39.730033800326076,-121.84518098831178?z/17?lvl/0)



### Transportation & Parking

<!---

* Parking Structure I provides the easiest access to Eureka Hall. [Click here for a map.](https://www.google.com/maps/d/u/0/edit?mid=1T37DrPBRhMhvMuvecZpQqAjh7Ilq63c&usp=sharing) 
* Day parking is available for a small fee using the [PayByPhone app](https://www.paybyphone.com/drivers/how-it-works#step2). All student parking spaces double as day-use spaces for visitors.

--->

* There is metered parking (free on weekends) on Citrus Ave and Legion Ave. 
* There is additional free street parking near the Gateway Science Museum. 
* Please don't park in the Bidwell Mansion parking lot or in the residential areas.
* CSU, Chico offers some [further advice about parking](https://www.csuchico.edu/parking/where-to-park/where.shtml).


### When you get there

Please check in at registration desk, and grab your name tag and t-shirt (if you registered early) when you get in. It's helpful to students to be able to clearly identify consultants from participants. Judges will get a notepad and judging rubric along with their badge. 

<!---
# Who is at ASA DataFest @ Sacramento State 2023? 

- 30 participants 
- 8 consultants
- 3 judges

--->

## Contact

<!---

You are also welcome to join the event [Discord server](https://discord.gg/3Y33x6REXC). Your point of contact is Lauren Cappiello. Contact Lauren on Discord or via email at cappiello@csus.edu. Judges and consultants will receive additional contact information via email during the week leading up to the event. 
--->

Judges and consultants will receive additional contact information via email during the week leading up to the event. 


# Data

<span style="color:red">Please note that this information is currently TOP SECRET!!!</span> We do not want it getting out to anybody until all other locations are done with their DataFest in later weeks.

All **judges** will receive a link to a document containing information on the data. Please let Lauren know if you have not received the invite. Any consultants who would like access to this document, please contact Lauren to request access.

The data set itself will **not** be provided to any consultants. <span style="color:red">We request that all computers be left at home.</span>

## Social Media

Did you know that, this year, DataFest will be held at over 70 universities around the world?
DataFest takes place during a six-week window in the Spring, and different universities hold
their event at different times.

An essential ingredient of Datafest is that the data be a surprise. There are several reasons for this. One is that it ensures that all teams start on an equal footing. Another is that, even if you research the organization that donated the data, you might still be totally unprepared for the context of the data (and maybe less prepared than had you known nothing!) Finally, it is simply more fun.

You are encouraged to share your excitement on social media and thank our sponsors. 
The official Twitter hashtag is #ASADatafest22 However...

PLEASE KEEP THE SECRET UNTIL MAY 4th! Teams that leak the name or any information
about the identify of the data donor will be disqualified!

Please do not post pictures that reveal any charts/graphs/tables/summaries/models that might
reveal the data donor.


# Consulting

The most important thing is to keep the mood light and encouraging! We suspect by sometime Saturday afternoon things might seem rather dire to some of the students.

On Friday night, students will be busy trying to make sense of the data. We expect that some of them might have technical problems with getting started (loading the data, viewing it, etc.). Throughout the weekend the teams will be on their own, though we might have intermittent “check ins”. We imagine they will get stuck and need advice. Sometimes, the advice could be highly technical and, depending on your background, outside your expertise. Don't worry. They know that you are not there to solve their problems, but to offer advice. See if you can steer them towards standard problem-solving techniques: break the problem into smaller pieces, go online for advice, etc. Guide them to think about context. What sort of distribution do they expect? Why? What might cause that? How does that compare to what they saw?

This is a competition, but it is supposed to be friendly and collaborative, so don't worry about revealing any special knowledge. This is not an exam, and so if someone asks, please answer if you can, and don't worry about other teams over hearing. I'm hoping that, after the first evening, teams will be sharing basic technical advice on their own.

Everyone is welcome to the presentations and award ceremony.

### A note about software

Most students will use R or Python but we also expect many to use SAP, Matlab, SAS, Excel, JMP, etc. as well. If asked for support on a platform you’re not familiar with, simply stating so is sufficient. If asked for support on a platform you are familiar with, you are welcomed to assist at any capacity you feel comfortable/up to -- from talking through the approach at a high level to sitting down and coding with them.

## Schedule

The schedule is at https://norcaldatafest.netlify.com/schedule/.

Registration opens at 5:00pm on Friday. The data presentation starts at 6:00. Sunday presentations start at 10:30am. 

We expect presentations to take approximately one hour, but ask judges to plan to be at the event from 10:00am - 12:30pm. 

All parties are welcome to attend the introduction to the data and the judging event. 

You should have received a schedule of consultant hours via email. 

<!---
A more detailed schedule of consultant and coordinator hours is in progress and will be posted and emailed to you prior to the event. 

can be found [in this Google document](https://docs.google.com/spreadsheets/d/1BA_FlTaCEctfSfXAAheNxecT38ykV2_xMJ6Ee92ek0g/edit?usp=sharing). If your schedule is incorrect (or you want to add more hours) please contact Robin directly. 

--->

## Judging

There are three prize categories:

- Best Insight
- Best Visualization
- Best Use of Outside Data

The latter category is meant to encourage students to find supporting information and/or data beyond what we give them.

An optional "Judges Choice" will be available to the judges to use if desired. 

Teams will have 5 minutes (4 min presentation + 1 min Q&A) and 2 slides to make their case. Some teams may also submit a 1 page write up with their presentation. This paper will be printed out and provided to you before judging starts. 

At least one helper will also be in the room with you to run the session, keep time, etc. You will also be given a judging pack including a rubric and notepad to help keep things straight when you pick up your badge. It’s strongly recommended that you make note of teams that are especially strong as you're watching the presentations so that the deliberation conversation can be as efficient as possible.

## Feedback

ASA DataFest has become an annual event that is now being officially sponsored by the American Statistical Association and held at numerous locations with participation from a large number of universities. We hope to grow the event further in the coming years. With that in mind, please send us any advice or constructive criticisms that will help us improve this event in the future to cappiello@csus.edu or to datascience@csuchico.edu. 

Our primary goal is to provide a rewarding experience for the undergraduates, an experience that sharpens their analytical skills and gives them some confidence that they can take what they learn here out into the real world.
